services:
  memory-postgres:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: memory
      TZ: Asia/Shanghai
    volumes:
      - memory_pgvector17_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d memory" ]
      interval: 1m
      start_interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - memory_network

  memory:
    image: ghcr.io/marvekw/insightmemory:latest
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "8010:8010"
    environment:
      TZ: Asia/Shanghai
    depends_on:
      memory-postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8010/health" ]
      interval: 1m
      start_interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - memory_network

volumes:
  memory_pgvector17_data:


networks:
  memory_network:
    driver: bridge
